### ISSUE TITLE
Issue with the global variable used to grab fetch

### ISSUE THREAD

**Issue by alexjeffburke** [gustavnikolaj/fetchception#66]
Hey,

I was trying to use `fetchception` with mocha configured to test a module for the web. In this configuration, I create a window object in the test suite and attach `fetch` and `Response` to it. The frontend code behaves correctly.

However, it seems that fetchception hard codes the node `global` object as the one it will read fetch from which means that, in practice, the test suite needs to assign `fetch` to both global and window, and that doesn't feel quite right.

My feeling is that fetchception should handle this correctly - I believe it has become tightly coupled to jest where (IIRC) they play games to make window and global the same object.

Happy to submit a PR if we can agree a solution :)

**Comment by alexjeffburke** [comment]
Update: fetchception attaches its instrumented version of `fetch` to `global`, so the only way of making this work correctly while keeping pure browser code referencing window is to place `global.window = global` in the test file somewhere - I opted for in a `before()` block.

**Comment by gustavnikolaj** [comment]
We probably don't want to do `global.window = global` in fetchception - that would be a bit rude to the consumers... :-)

Could we look for references to fetch on both `global` and `window` and remember where we found it, so we can substitute the references back and forth?

Maybe just doing the same substitution on both objects?

```js
var hasGlobal = typeof global === 'object';
var origGlobalFetch = global && global.fetch;
var hasWindow = typeof window === 'object';
var origWindowFetch = window && window.fetch

// Setup
if (hasGlobal) {
  global.fetch = mockedFetch;
}
if (hasWindow) {
window.fetch = mockedFetch;
}

// Teardown
if (hasGlobal) {
  global.fetch = origGlobalFetch;
}
if (hasWindow) {
  window.fetch = origWindowFetch;
}
```

**Comment by gustavnikolaj** [comment]
I came across this issue just now, and thinking about it again, isn't this just an issue of you requiring fetchception before you setup your faux-window object? I am pretty sure that fetchception works out of the box with jest due to jest setting up the jsdom environment prior to fetchception being loaded.

**Comment by alexjeffburke** [comment]
I'm really trying to remember what the issue was, but it's long enough ago that I'm not sure.

You mentioned jest, but I think I was using this with mocha where a new DOM environment gets set up for every test. Reading my own notes back, I think there was also something around it trying to pull `Response` from global if it's on node, but the code being tested is browser only. I seem to recall that wrinkle with `Response` being what made it gnarly, but I'm not sure I have access to the repo that demonstrated it any more. Can look around the open source stuff to see whether it spilled out there if you're keen though :)

**Comment by gustavnikolaj** [comment]
The jest comment was just reasoning about what the issue might be. :-) What jest does is injecting browser-globals sourced from a JSDOM env onto node's `global` object. If you did the same in your mocha-setup, you should be able to get it working just by ensuring proper load order. It works flawlessly in jest, at least the last time I tried it, which, admittedly, is a while ago.

I'm open to do changes to it, but I'd prefer having a good use-case for reference, instead of guessing at the solution, so unless it's still relevant to you, I'd prefer just closing this issue and opening it again once it becomes relevant :-)

The entirety of the glue used is currently: 
- https://github.com/gustavnikolaj/fetchception/blob/02b7de86b45207fc21af13cf9ccfa4c183de22e6/index.js#L192-L193
- https://github.com/gustavnikolaj/fetchception/blob/02b7de86b45207fc21af13cf9ccfa4c183de22e6/index.js#L210

**Comment by alexjeffburke** [comment]
Yeah, tend to agree that we need a clear case to be able to reason about things so lets close it for now.

One thing I might suggest is that we add a check for both the necessary globals being defined - currently, fetchception checks for `global.fetch` (https://github.com/gustavnikolaj/fetchception/blob/master/index.js#L132) but internally also relies on `global.Repsonse` - perhaps it's worth adding `if (!global.Response) { ... }` so any users get a clear message in that case too? Seem to remember the failure mode isn't pretty if you end up with one and not the other (ahhh, which was actually a separate related problem - if you try to use browser and use `node-fetch` to polyfll fetch on node by doing `global.fetch = require('nod-fetch')` that isn't enough).

**Comment by gustavnikolaj** [comment]
We spoke outside GitHub and agreed to close this issue for now. If we have it come up again we will look at it again, and find a solution.
